"""empty message

Revision ID: 1dbee7d9cf71
Revises: 
Create Date: 2024-05-16 11:27:25.415848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dbee7d9cf71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'taille5')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('taille5', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
